name: import_sorter
description: Automatically organize your dart imports
version: 5.0.0
repository: "https://github.com/fluttercommunity/import_sorter"
homepage: "https://mattglei.ch"
maintainer: Matthew Gleich (@gleich)

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  args: ^2.7.0
  tint: ^2.0.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0


import_sorter:
  emojis: true
